#!/bin/bash

USERID=$(id -u)

#echo "USER ID is: $USERID"

#ne is special variable
VALIDATE(){
    if [ $1 -ne 0 ]
    then 
        echo "$2 is ..FAILED"
        exit 1
    else 
        echo "$2 is ..success"
    fi        
}
if [ $USERID -ne 0 ]
then 
    echo"Please run the script with root previlages"
    exit 1
fi

dnf list installed git #list all installed packages in git

if [ $? -ne 0 ]
then 
    echo "Git is not installed ,going to install it.."
    dnf install git -y
    VALIDATE $? "Installimg GIT" 
else
    echo "Git is already installed.."
fi

dnf list installed mysql

if [ $? -ne 0 ]
then 
    echo "MySql is not installed..going to install"
    dnf install mysql -y
    VALIDATE $? "Installimg MySQL"       
else
    echo "MySql is already installed."   
fi          